### ISSUE TITLE
will this extension support mac?!

### ISSUE THREAD

**Issue by Phymiu** [Delusoire/bespoke#1]

**Comment by Delusoire** [comment]
The CLI is written in Go and is designed to be cross-platform. Most of the functionality is already available for all major platforms (Mac included). The only hurdle left is to implement custom URI schemes for Mac and Linux, but this is only required if you want the ability to install/remove modules (add-ons) from within the Spotify interface.

**Comment by Phymiu** [comment]
mac user how to install this client, i cant find mac instrucion  in the readme

**Comment by Delusoire** [comment]
You should already be able to use it on macOS (although I haven't tested it myself). You can refer to the updated [README](https://github.com/Delusoire/bespoke/blob/main/README.md) for more instructions on how to set this up. Keep in mind this project is still at a rudimentary stage, it is only functional but the installation process will eventually get easier as I keep smoothing its rough edges.

**Comment by Phymiu** [comment]
> You should already be able to use it on macOS (although I haven't tested it myself). You can refer to the updated [README](https://github.com/Delusoire/bespoke/blob/main/README.md) for more instructions on how to set this up. Keep in mind this project is still at a rudimentary stage, it is only functional but the installation process will eventually get easier as I keep smoothing its rough edges.你应该已经可以在 macOS 上使用它了（尽管我自己还没有测试过）。您可以参阅更新的自述文件以获取有关如何设置的更多说明。请记住，这个项目仍处于初级阶段，它只是功能性的，但随着我不断平滑其粗糙的边缘，安装过程最终会变得更容易。

<img width="697" alt="image" src="https://github.com/Delusoire/bespoke/assets/143943457/f307f3eb-a475-4fa0-8637-ed193c1774c4">
i just  try to install, but stuck here. idk how to fix. plz help me

**Comment by Delusoire** [comment]
I forgot to include the quotes around the path. The command should be: `git clone --depth 1 --recurse-submodules "~/Library/Application Support/bespoke"`

**Comment by Phymiu** [comment]
<img width="697" alt="image" src="https://github.com/Delusoire/bespoke/assets/143943457/9aaa5e0e-36ea-4084-8f9a-c506e8230f01">
still dont work :-(

**Comment by Delusoire** [comment]
My bad, i'm not very familiar with zsh, apparently tilde expansion doesn't work inside strings. `git clone --depth 1 --recurse-submodules "$HOME/Library/Application Support/bespoke"`

**Comment by Phymiu** [comment]
<img width="1213" alt="image" src="https://github.com/Delusoire/bespoke/assets/143943457/6dc46738-0b46-4061-827a-f8af33723032">
i have download the zip on github and rename, put it the path"/Users/phymiu/Library/Application Support/bespoke",
fortunately, the path in terminal looks right, but cant find my file.

**Comment by Delusoire** [comment]
You shouldn't have anything in that directory. Can you delete that directory and try the last command again?

**Comment by Phymiu** [comment]
thans for help! It works ,but i stuck at here
<img width="953" alt="image" src="https://github.com/Delusoire/bespoke/assets/143943457/839f9fc7-26a9-4968-a7ee-602bfc384941">

**Comment by Delusoire** [comment]
You should add the "$HOME/Library/Application Support/bespoke/cli" path to your "PATH" environment variable, I have a step for this in the readme, but I can't extensively list every command for every environment out there. After some googling, I think that this could work: `echo "$HOME/Library/Application Support/bespoke/cli" >> /etc/paths`

**Comment by Phymiu** [comment]
Followed your steps, I reached here, but cant find bespoke still.
Thans for help!
<img width="953" alt="image" src="https://github.com/Delusoire/bespoke/assets/143943457/bcbb9078-102f-4dcc-9c5a-511aa5927d34">

**Comment by Delusoire** [comment]
You need to build the project, in bespoke/cli/ run `go build`

**Comment by Phymiu** [comment]
Thanks for help. Im giving up for this though. Hope you a nice day!
