### ISSUE TITLE
feature request: `init` not requiring elevation

### ISSUE THREAD

**Issue by ohitstom** [Delusoire/bespoke#10]
or atleast offer to elevate when needed?

**Comment by Delusoire** [comment]
I'm not entirely sure why that's even happening. It seems like the permission error only arises when Spotify is already running?  Can you try investigating that? If it's the case then I can ask to kill Spotify before applying the patches.

**Comment by ohitstom** [comment]
> I'm not entirely sure why that's even happening. It seems like the permission error only arises when Spotify is already running?  Can you try investigating that? If it's the case then I can ask to kill Spotify before applying the patches.

can do, it's late but I will early morning 👍

side note how do you plan on killing the process cross platform if this is the case?

**Comment by Delusoire** [comment]
> side note how do you plan on killing the process cross platform if this is the case?

Go can find a process by its PID and then kill it, using the os package. Now finding the PID requires having a list of all running processes which is an entirely different beast, one has to delve into platform specific syscalls but luckily there are some 3rd party packages that do that for you [go-ps](https://github.com/mitchellh/go-ps).

**Comment by ohitstom** [comment]
sorry for the wait:
![image](https://github.com/Delusoire/bespoke/assets/22730962/6d435bb6-fe49-4031-a147-a4a1f9aa525d)

same error regardless of if spotify is running or not, theres also this weird glitch where if it fails to init then bespoke thinks its initialized regardless and when going to try initializing again you have to run fix before:
![image](https://github.com/Delusoire/bespoke/assets/22730962/69c5d700-0d44-4676-b93a-35ee6c82a60e)

**Comment by ohitstom** [comment]
https://github.com/golang/go/issues/22874
^ this seems promising

**Comment by Delusoire** [comment]
Huh, then it seems like we can't do anything about it. And asking people to always run only this command in an elevated shell is a bit much. And this complicates the auto-start process too. Maybe we can just ask users to enable developer mode?
![Screenshot_2024-03-25-10-56-29-411-edit_com.android.chrome.jpg](https://github.com/Delusoire/bespoke/assets/71462480/6921dc29-bead-44bb-90e7-e1eb58dbf96c)
It seems like that could solve this?
https://github.com/golang/go/commit/c23afa9ddb1180b929ba09a7d96710677a2a4b45

**Comment by ohitstom** [comment]
i know you are going to hate this because of exec but windows has a thing known as "junctions" which are identical to symlinks but do not need elevation:

```go
func createJunction(source string, target string) error {
	cmd := exec.Command("cmd", "/C", "mklink", "/J", target, source)
	output, err := cmd.CombinedOutput()
	if err != nil {
		return err
	}
	if strings.Contains(string(output), "created") {
		return nil
	}
	return os.ErrPermission // failed to create junction
}

links := map[string]string{"hooks-out": "hooks", "modules": "modules"}
for src, dest := range links {
folderSrcPath := filepath.Join(paths.ConfigPath, src)
folderDestPath := filepath.Join(destXpuiPath, dest)
if runtime.GOOS == "windows" {
        log.Println("Creating junction", folderSrcPath, "->", folderDestPath)
	err := createJunction(folderSrcPath, folderDestPath)
	if err != nil {
		log.Fatalf("Failed to create junction: %v", err)
	}
} else {
	log.Println("Creating symbolic link", folderSrcPath, "->", folderDestPath)
	err := os.Symlink(folderSrcPath, folderDestPath)
	if err != nil {
		log.Fatalf("Error creating symbolic link: %v", err)
	}
}
}
```

![image](https://github.com/Delusoire/bespoke/assets/22730962/12e07152-d198-4b4f-b151-d02ba26cd3f6)

fingers crossed theres a way to do this without exec using windows dlls but i cant find anything online

**Comment by Delusoire** [comment]
> >  This looks like it would work. [golang/go@c23afa9](https://github.com/golang/go/commit/c23afa9ddb1180b929ba09a7d96710677a2a4b45)
> 
> im unfamiliar with how golangs package system works, is this not the same function we are already using?
> 
> unless you mean use those functions to test if developer mode is enabled and if not prompt the user to?
> 
> 

That's go's standard library, i'm simply referencing it because it prompts that enabling developer mode will fix this issue

**Comment by Delusoire** [comment]
> i know you are going to hate this because of exec but windows has a thing known as "junctions" which are identical to symlinks but do not need elevation:
> 
> ```go
> func createJunction(source string, target string) error {
> 	cmd := exec.Command("cmd", "/C", "mklink", "/J", target, source)
> 	output, err := cmd.CombinedOutput()
> 	if err != nil {
> 		return err
> 	}
> 	if strings.Contains(string(output), "created") {
> 		return nil
> 	}
> 	return os.ErrPermission // failed to create junction
> }
> 
> links := map[string]string{"hooks-out": "hooks", "modules": "modules"}
> for src, dest := range links {
> folderSrcPath := filepath.Join(paths.ConfigPath, src)
> folderDestPath := filepath.Join(destXpuiPath, dest)
> if runtime.GOOS == "windows" {
>         log.Println("Creating junction", folderSrcPath, "->", folderDestPath)
> 	err := createJunction(folderSrcPath, folderDestPath)
> 	if err != nil {
> 		log.Fatalf("Failed to create junction: %v", err)
> 	}
> } else {
> 	log.Println("Creating symbolic link", folderSrcPath, "->", folderDestPath)
> 	err := os.Symlink(folderSrcPath, folderDestPath)
> 	if err != nil {
> 		log.Fatalf("Error creating symbolic link: %v", err)
> 	}
> }
> }
> ```
> 
> ![image](https://github.com/Delusoire/bespoke/assets/22730962/12e07152-d198-4b4f-b151-d02ba26cd3f6)
> 
> fingers crossed theres a way to do this without exec using windows dlls but i cant find anything online - havent tested it but this looks like it might do the job(?): https://github.com/nyaosorg/go-windows-junction
> 

Honestly, the package you're using looks unmaintained and isn't all that popular at all. I think that enabling the developer mode ourselves is the simplest and best approach here. All it takes is some registry manipulation which we're already doing for the custom URI scheme

**Comment by ohitstom** [comment]
> Honestly, the package you're using looks unmaintained and isn't all that popular at all. I think that enabling the developer mode ourselves is the simplest and best approach here. All it takes is some registry manipulation which we're already doing for the custom URI scheme

i respectfully disagree, the windows spec for this kind of stuff never changes, maintainability isnt really an issue....
this is a very quick fix and doesnt require us adding extra steps for the user :/

idk i think this solution would work great - using junctions in general that is maybe you disagree on this specific package

**Comment by JustSxm** [comment]
Personally, the fact that Spicetify does not update itself is the biggest pain point of the entire project.

**Comment by ohitstom** [comment]
> Personally, the fact that Spicetify does not update itself is the biggest pain point of the entire project. (as a user)

that is irrelevant to this discussion

**Comment by Delusoire** [comment]
I ended up implementing the approach I mentioned above, this also came with a change in command names. A new "apply" command was introduced which is the equivalent of the old "init". The new "init" performs one-time initialization tasks like setting up the custom URI scheme and enabling developer mode on Windows. The "init" command also asks the user to run be ran in an elevated shell in case of failure. I tested this and it seems to be working very well.

**Comment by ohitstom** [comment]
> I ended up implementing the approach I mentioned above, this also came with a change in command names. A new "apply" command was introduced which is the equivalent of the old "init". The new "init" performs one-time initialization tasks like setting up the custom URI scheme and enabling developer mode on Windows. The "init" command also asks the user to run be ran in an elevated shell in case of failure. I tested this and it seems to be working very well.

upsetting and difficult for the end user but whatever, not looking forward to needing to elevate every time I want to apply when junctions exist.

**Comment by Delusoire** [comment]
This is not what i said, you only need to elevate for bespoke init, not for bespoke apply, but whatever...

**Comment by ohitstom** [comment]
> This is not what i said, you only need to elevate for bespoke init, not for bespoke apply, but whatever...

but the user is still required to elevate for something they shouldn't, for example most users won't run the install script with admin as it breaks permission stuff, then they will be required to reopen the terminal elevated just to init before applying? 🤔

**Comment by ohitstom** [comment]
> This is not what i said, you only need to elevate for bespoke init, not for bespoke apply, but whatever...

but the user is still required to elevate for something they shouldn't, for example most users won't run the install script with admin as it breaks permission stuff, then they will be required to reopen the terminal elevated just to init before applying? 🤔

**Comment by Delusoire** [comment]
It will all be handled by the install script. You can easily run a single command as Administrator with `Start-Process -FilePath "powershell" -Verb RunAs` and exit the elevated shell afterwards.

**Comment by ohitstom** [comment]
> It will all be handled by the install script. You can easily run a single command as Administrator with `Start-Process -FilePath "powershell" -Verb RunAs` and exit the elevated shell afterwards.

orrrr we could use junctions and not have to do that
