### ISSUE TITLE
bespoke has no command apply

### ISSUE THREAD

**Issue by Simi2437** [Delusoire/bespoke#15]
I cannot get bespoke to work with my normal spotify installation. Also i cannot run bespoke apply, maybe the readme is allready outdated ? 
 .\bespoke.exe --help
Bespoke is a CLI utility that empowers the desktop Spotify client with custom themes and extensions

Usage:
  bespoke [flags]
  bespoke [command]

Available Commands:
  completion  Generate the autocompletion script for the specified shell
  daemon      Run daemon
  dev         Patch Spotify to open in app-developer mode next time it launches
  fix         Fix your spotify installation
  help        Help about any command
  init        initialize bespoke for Spotify
  init        initialize bespoke
  path        Print bespoke config
  pkg         Manage modules
  protocol    Internal protocol handler
  run         launch Spotify with your favorite addons
  sync        Update bespoke from GitHub

Flags:
      --auto-update             Toggle auto updates for bespoke
      --config string           config file (default is C:\Users\simon\AppData\Local\bespoke\config.yaml) (default "C:\\Users\\simon\\AppData\\Local\\bespoke\\config.yaml")
  -h, --help                    help for bespoke
  -m, --mirror                  Mirror Spotify files instead of patching them directly
      --spotify-config string   Override Spotify config folder (containing prefs & offline.bnk) (default "C:\\Users\\simon\\AppData\\Local\\Spotify")
      --spotify-data string     Override Spotify data folder (containing the spotify executable) (default "C:\\Users\\simon\\AppData\\Roaming\\Spotify")

Use "bespoke [command] --help" for more information about a command.

**Comment by Simi2437** [comment]
I found the line in the go file where the 2 inits come from. Thats a minor bug. But still when i run bespoke apply - no error message - And i open Spotify. Window stay black and freeze. No marketplace what so ever.

**Comment by Simi2437** [comment]
Ok Window is not frozen but i see only the settings points nothing else

**Comment by Delusoire** [comment]
Confirmed. Small oversight from my part. will fix soon.

**Comment by wdarea51** [comment]
Any update on this... i really really want to sort my playlists by sort count and cant for the life of me figure out how to do it and your extension is the only one that can sort playlists in the extension marketplace and it currently doesnt work... but anyway thanks for the extension and please fix as soon as you are able to and have the time to do so, it would be MUCH appreciated.

**Comment by Simi2437** [comment]
Yeah waiting also for this to work

**Comment by Delusoire** [comment]
I've pushed the relevant commits to fix this issue some days ago. Make sure that your local repository clone is up-to-date, then build the cli again. Hope this solves your issues.

**Comment by Simi2437** [comment]
@Delusoire I pulled main and did init and apply. Now the commands do work. But still after applying my spotify is black. There are only the three dots top left and the normal minimize maximize and close buttons. Everything else is black.
I'm on Windows and have the newest spotify version.

**Comment by Delusoire** [comment]
`bespoke init` should be run in a privileged shell,
and `bespoke apply` in a normal shell.

**Comment by Simi2437** [comment]
i did am i the only one with that problem ? Spotify turns just black.
![grafik](https://github.com/Delusoire/bespoke/assets/31888669/9714b03b-18ee-415e-8b1d-82996f05a440)
