### ISSUE TITLE
Why an alternative to spicetify?

### ISSUE THREAD

**Issue by JustSxm** [Delusoire/bespoke#2]
Hello,

I was wondering why you've decided to create an alternative to spicetify? Is there things making it too hard for extensions support  / is it how spicetify was designed?

Its unfortunate as theres a lot of extensions I was using from you that I like which started breaking. This also means that extensions created by others wont be available.

**Comment by JustSxm** [comment]
On top of that, I appreciate your work, but if you want this fork to take over spicetify, meaninful commit messages and documentation would be required

**Comment by Delusoire** [comment]
> Hello,

Hi, 👋

> I was wondering why you've decided to create an alternative to spicetify? Is there things making it too hard for extensions support / is it how spicetify was designed?

Spicetifty v2 has suffered from a lot of problems. Its javascript wrapper is unmaintainable, all the API logic is crammed into a single messy file filled with ugly hacks and workarounds. Moreover, Spicetify v2 extensions only have access to a limited scope of APIs and functions with no real access to Spotify's internals. This "fork" takes some very different approaches to patching Spotify, loading the modules, managing dependencies ... And takes advantage of modern javascript/typescript features like ES modules, url imports, etc.

> On top of that, I appreciate your work, but if you want this fork to take over spicetify, meaninful commit messages and documentation would be required

I've been in contact with the active Spicetify maintainers and we've been talking about making bespoke the next major release of Spicetify. There are still some steps to take before releasing an official Spicetify v3 beta,
and a lot of testing to do, but we'll get there eventually.

As for the commit messages, the structure of the project is changing fast. Writing commit messages will considerably slow down development. But as we approach a stable release, I will make sure to follow the standard commit naming conventions.

The Spicetify documentation is mostly outdated, and will need to be rewritten anyway.

> Its unfortunate as theres a lot of extensions I was using from you that I like which started breaking. This also means that extensions created by others wont be available.

Most of the extensions that I see on Marketplace are broken on latest Spotify (including some of my old extensions). Other extension/custom app developers have expressed interest in the new APIs & module system. And I've already ported over a considerable amount of extensions to bespoke (If there are any extensions that you'd like to see added to bespoke then you can just request them in an issue).

I hope this answers all your questions. 😄

**Comment by JustSxm** [comment]
It does! Excited to see what you do with bespoke!
