### ISSUE TITLE
feature request: chainable commands

### ISSUE THREAD

**Issue by ohitstom** [Delusoire/bespoke#9]
![image](https://github.com/Delusoire/bespoke/assets/22730962/b5e9d7cd-5ef5-4ba0-a06e-462fcb81877c)

**Comment by Delusoire** [comment]
I present to you: the "&&" operator. It works on all major shells, including but not limited to: pwsh, sh, bash, zsh, fish ...
 In more seriousness, you almost never have to run more than a single command at a time. But if you're the kind of person to use yay over paru for the one less character to type then you can write yourself some shell aliases. 😃

**Comment by ohitstom** [comment]
> I present to you: the "&&" operator. It works on all major shells, including but not limited to: pwsh, sh, bash, zsh, fish ... In more seriousness, you almost never have to run more than a single command at a time. But if you're the kind of person to use yay over paru for the one less character to type then you can write yourself some shell aliases. 😃

why was this a feature in v2 then 🤔
